### ISSUE TITLE
Views shown as Tables

### ISSUE THREAD

**Issue by semihpolat** [zernonia/supabase-schema#3]
Hi, Firstly it is great job! we needed it too much! 

The issue is I have tables and views from tables but when I wanna export SQL views shown as tables.

**Comment by zernonia** [comment]
Hi @semihpolat . Glad to hear that you are using this tool! And thank you so much for this issue.

I realized that `View`  is also generated in the OpenAPI schema, thus signaling that it is a Table (which is not).
I will look into this and try to differentiate Tables and Views on the dashboard, so that users can differentiate easily,
and finally export the appropriate tables only.


Thank you! 😄

**Comment by zernonia** [comment]
Fix the `View` showing in Export SQL. Thank you!

https://github.com/zernonia/supabase-schema/commit/b5cb8d8bfbe1c3f1d9a5cc75d2fe8176cf5db746
